version: '2'

networks: 
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local

services:

  traefik:
    container_name: traefik
    hostname: traefik
    build: traefik/
    image: sofwerx/traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      HTTP_PORT: "80"
      HTTPS_PORT: "443"
      REST_PORT: "8080"
      EMAIL: "ian@sofwerx.org"
      DNS_DOMAIN: "swx-gpu.devwerx.org"
      SUBDOMAINS: '"swx-gpu.devwerx.org", "orient.swx-gpu.devwerx.org", "traefik.swx-gpu.devwerx.org", "staoi.swx-gpu.devwerx.org", "dta.swx-gpu.devwerx.org"'
    volumes:
      - traefik-ssl:/ssl
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.swx-gpu.devwerx.org"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  orient:
    build: orient/
    image: sofwerx/orient
    restart: always
    container_name: orient
    hostname: orient
    environment:
      PEER_CONFIG: "${PEER_CONFIG}"
      NIFI_CONFIG: "{ enabled: true, url: 'http:///nifi' }"
      SECURE_PORT: 443
      HTTP_PORT: 9999
    ports:
      - 9999:9999
    labels:
      - "traefik.backend=orient"
      - "traefik.port=9999"
      - "traefik.frontend.rule=Host:orient.swx-gpu.devwerx.org"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

